name: Test
on: [push, pull_request]
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - name: Test
        env:
          MONGODB: ${{ vars.MONGODB }}
          DB_NAME: ${{ vars.DB_NAME }}
        run: go test -v ./...